### PR TITLE
Add more devices definitions

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
@dgoetz can this get in or should I close? :-)

**Review by dgoetz — APPROVED** [review]
Looks good to me.

**Comment by dgoetz** [comment]
I approved and merged it, but the plugin needs a new maintainer as @dnsmichi left us. I will going to ask internally.

**Comment by dnsmichi** [comment]
@dgoetz I never was a maintainer of 99% of the Netways plugins, except for btfrs and tinkerforge.

People still confuse the initial first commit, which happened with my git details when splitting the single CS plugin repository into multiple ones. This must have been in 2013 or 2014 when Icinga Exchange was built. 

TL;DR - all plugins need maintainers, this was an open task before I changed jobs.

**Pull request merged**
